### ISSUE TITLE
Component is not rendered when the table is sorted

### ISSUE THREAD

**Issue by marc-1254** [datenhahn/componentrenderer#29]
First of all thanks for the great add on. As long the table is not sorted by a column it works perfectly.
But I have the issue, that when sorting the table descending by any column, the rendered component disappears. It is not in the DOM-Tree anymore.
When resorting the columns ascending they appear again.

Somehow the components are only rendered if the container is not sorted or if the sort is ascending only.

Tried it with the latest Version of Vaadin and this add-on.
As the Components are not in the DOM anymore it shouldn't be related to the browser.

**Comment by datenhahn** [comment]
Thanks for the report. I am busy currently but will have a look at the problem next week

**Comment by datenhahn** [comment]
Can you post some example code? I just tried to reproduce the bug with Vaadin 7.7.0 and componentrenderer version 1.0.2 on the first page of the demo application, but sorting worked fine.

**Comment by datenhahn** [comment]
could not replicate the bug (see my other comments), closing the ticket now, please just reopen the bug if the problem still exists and you can supply some sample code
