### ISSUE TITLE
Grid only shows first Component (label) from layout when spacing is enabled

### ISSUE THREAD

**Issue by Siedlerchr** [datenhahn/componentrenderer#33]
First of all, thanks for the cool component!
I have a grid which is created using the  ComponentGridDecorator and backed by a BeanItemContainer.
For the display in the grid I have a simple vlayout with 2 labels, first one is html, 2nd text.

Grid itself is set to 100%x100% after adding the data etc.
The vlayout with the labels is also set to 100%x100%

However, when I enable spacing in the vlayout only my first label is shown:
Any idea if this a problem on my side or with the component?

![withspacing](https://cloud.githubusercontent.com/assets/320228/20261498/5707bdca-aa5e-11e6-8837-cb3851d27789.png)

No spacing:
![withtopicsandnospaces](https://cloud.githubusercontent.com/assets/320228/20261506/5f98a85a-aa5e-11e6-84db-f37c5feb0489.png)

**Comment by datenhahn** [comment]
Probably the additional spacing pushes the 2nd Text completely out oft the visible area of the row. Grid doesn't support variable row heights, but you can set the height of all rows to a different value:

http://stackoverflow.com/questions/34438195/vaadin-grid-row-height

**Comment by datenhahn** [comment]
closing the issue, assuming setting the row height fixed it, if you mean't something different, just reopen the ticket with more details
