### ISSUE TITLE
Porting ComponentRenderer to Vaadin 8

### ISSUE THREAD

**Issue by datenhahn** [datenhahn/componentrenderer#35]
With Vaadin 8 coming up, it is time to port the ComponentRenderer to Vaadin 8

Some thoughts about porting:

1. Try to just make it work as similar as possible like before
2. Analyse how Grid Component changed from Vaadin 7 to Vaadin 8
3. Try to throw away workarounds and make it feel natural to Vaadin 8 concepts
4. Think about a soft migration path and write tutorial for migration

The goal is to make migration soft for current Users, but also to embrace Vaadin 8 concepts. A couple of possibilities come in mind:

- explore the Vaadin 8 compatibility Layer and release a Version being as close to existing one as possible
- have a separate Version which embraces Vaadin 8 concepts (different build, or other Class in same package)

**Comment by datenhahn** [comment]
I will update the status here from time to time.

Current Status:

- Created Branch for Vaadin 8 Version
- Started trying to make it build with Vaadin 8 (not using the compatibility layer for now), this still the very beginning and will take quite some time

**Comment by mht-dotsource** [comment]
Hi @datenhahn,
do you have a roadmap? When will the branch released?
Ty

**Comment by datenhahn** [comment]
Hi @mht-dotsource ,

I changed my approach and used the vaadin compatibility layer for now. Please note that I consider this status still experimental as there might appear some bugs when used in reallife projects with vaadin 8. After a couple of months I would move it to beta, then again after some months without bugs to stable. Anyway I would be happy if you try it out and report if you encounter bugs:

https://vaadin.com/directory#!addon/componentrenderer

I also wrote a blog-post mentioning some small pitfalls I encountered during the migration. Overall it was pretty straightforward:
https://iniy.org/?p=662

**Comment by datenhahn** [comment]
Closing this ticket as the renderer is ported to Vaadin 8 albeit using the compatibility layer. Vaadin announced to support components in the grid from Vaadin 8.1 on. maybe I still will do a full rewrite of the renderer just for fun (opened ticket #36)
